# SPDX-FileCopyrightText: Robert Nelson <robertcnelson@gmail.com>
# SPDX-License-Identifier: MIT
#
# You can find the Docker source files at https://openbeagle.org/beagleboard/ci-docker-images

variables:
  TRANSFER_METER_FREQUENCY: "5s"
  GIT_STRATEGY: "clone"
  GIT_DEPTH: 1
  REGISTRY_BASE: "registry.gfnd.rcn-ee.org:5000/ci"

before_script:
  - export PATH=/usr/lib/ccache:$PATH
  - export CCACHE_DIR=/dev/shm/my-ccache-in-memory
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"
  - git config --global advice.detachedHead false
  - df -h /dev/shm
  - touch .gitlab-runner

build-debian-14-arm64:
  image: $REGISTRY_BASE/beagle-devscripts-kernel-debian-14-arm64:latest
  cache:
    key: "$CI_PROJECT_NAME-debian-14-arm64"
    paths:
      - ccache.tar.zst
  tags:
    - docker-aarch64-rpi4-ci
  stage: build
  script:
    - ./tools/ci-debian-update.sh
    - ./tools/ci-setup-ccache.sh
    - ./build_u-boot.sh
    - ./tools/ci-cleanup-ccache.sh

pages:
  image: $REGISTRY_BASE/beagle-devscripts-kernel-debian-13-arm64:latest
  cache:
    key: "$CI_PROJECT_NAME-debian-13-arm64"
    paths:
      - ccache.tar.zst
  tags:
    - docker-aarch64-rpi4-ci
  stage: build
  script:
    - ./tools/ci-debian-update.sh
    - ./tools/ci-setup-ccache.sh
    - ./build_u-boot.sh
    - ./tools/ci-cleanup-ccache.sh
    - apindex public
  artifacts:
    when: on_success
    paths:
      - public
  only:
    - main
