# SPDX-FileCopyrightText: Robert Nelson <robertcnelson@gmail.com>
# SPDX-License-Identifier: MIT
#
# You can find the Docker source files at https://openbeagle.org/beagleboard/ci-docker-images

variables:
  TRANSFER_METER_FREQUENCY: "5s"
  GIT_STRATEGY: "clone"
  GIT_DEPTH: 1
  REGISTRY_BASE: "registry.gfnd.rcn-ee.org:5000/ci"
  PROD_DISTRO_VER: "debian-13"

before_script:
  - export PATH=/usr/lib/ccache:$PATH
  - export CCACHE_DIR=/dev/shm/my-ccache-in-memory
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"
  - git config --global advice.detachedHead false
  - df -h /dev/shm
  - touch .gitlab-runner

.build_template:
  stage: build
  tags:
    - docker-aarch64-ci
  resource_group: $TARGET_LOCK_NAME
  script:
    - ./tools/ci-debian-update.sh
    - ./tools/ci-setup-ccache.sh
    - |
      if [ "$DISTRO_VER" = "debian-14" ]; then
        ./build_u-boot.sh || echo "Debian-14 build failed, but ignoring error."
      else
        ./build_u-boot.sh
      fi
    - ./tools/ci-cleanup-ccache.sh

build-debian-arm64:
  extends: .build_template
  parallel:
    matrix:
      - DISTRO_VER: ["debian-14", "ubuntu-24.04", "ubuntu-26.04"]
  image: $REGISTRY_BASE/beagle-devscripts-kernel-${DISTRO_VER}-arm64:latest
  variables:
    TARGET_LOCK_NAME: "lock-${DISTRO_VER}"
  cache:
    key: "$CI_PROJECT_NAME-${DISTRO_VER}-arm64"
    paths:
      - ccache.tar.zst
      - .last_build_sizes.txt

pages:
  extends: .build_template
  image: $REGISTRY_BASE/beagle-devscripts-kernel-${PROD_DISTRO_VER}-arm64:latest
  variables:
    TARGET_LOCK_NAME: "lock-${PROD_DISTRO_VER}"
  cache:
    key: "$CI_PROJECT_NAME-${PROD_DISTRO_VER}-arm64"
    paths:
      - ccache.tar.zst
      - .last_build_sizes.txt
  script:
    - !reference [.build_template, script]
    - apindex public
  artifacts:
    when: on_success
    paths:
      - public
  only:
    - main
