# SPDX-FileCopyrightText: Robert Nelson <robertcnelson@gmail.com>
# SPDX-License-Identifier: MIT
#
# You can find the Docker source files at https://openbeagle.org/beagleboard/ci-docker-images

variables:
  TRANSFER_METER_FREQUENCY: "5s"
  GIT_STRATEGY: "clone"
  GIT_DEPTH: 1
  REGISTRY_BASE: "registry.gfnd.rcn-ee.org:5000/ci"

before_script:
  - export PATH=/usr/lib/ccache:$PATH
  - export CCACHE_DIR=/dev/shm/my-ccache-in-memory
  - df -h /dev/shm
  - echo "Acquire::http::Proxy \"http://192.168.1.10:3142\";" > /etc/apt/apt.conf.d/00aptproxy
  - apt-get update
  - apt-get dist-upgrade -yq
  - apt-get install -yq ccache device-tree-compiler gcc-arm-linux-gnueabihf libgnutls28-dev python3-cryptography python3-dev python3-jsonschema python3-pycryptodome python3-pyelftools python3-setuptools python3-yaml swig uuid-dev yamllint
  - touch .gitlab-runner
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"
  - git config --global advice.detachedHead false

build-debian-14-arm64:
  image: $REGISTRY_BASE/beagle-devscripts-kernel-debian-14-arm64:latest
  cache:
    key: "$CI_PROJECT_NAME-debian-14-arm64"
    paths:
      - ccache.tar.zst
  tags:
    - docker-aarch64-rpi4-ci
  stage: build
  script:
    - ./tools/ci-setup-ccache.sh
    - ./build_u-boot.sh
    - ./tools/ci-cleanup-ccache.sh

pages:
  image: $REGISTRY_BASE/beagle-devscripts-kernel-debian-13-arm64:latest
  cache:
    key: "$CI_PROJECT_NAME-debian-13-arm64"
    paths:
      - ccache.tar.zst
  tags:
    - docker-aarch64-rpi4-ci
  stage: build
  script:
    - ./tools/ci-setup-ccache.sh
    - ./build_u-boot.sh
    - ./tools/ci-cleanup-ccache.sh
    - apindex public
  artifacts:
    when: on_success
    paths:
      - public
  only:
    - main
